# Generated by Django 5.2.4 on 2025-08-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_room',
            new_name='classroom',
        ),
    ]
